/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bce_jni_natives_BCENative */
#include "bcejni.h"

#ifndef _Included_bce_jni_natives_BCENative
#define _Included_bce_jni_natives_BCENative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bce_jni_natives_BCENative
 * Method:    setup
 * Signature: ([BI[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_setup
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     bce_jni_natives_BCENative
 * Method:    genPrivateKeys
 * Signature: ([B[BIII[[B)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_genPrivateKeys
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint, jobjectArray);

/*
 * Class:     bce_jni_natives_BCENative
 * Method:    encrypt
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_encrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     bce_jni_natives_BCENative
 * Method:    decrypt
 * Signature: ([B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_decrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     bce_jni_natives_BCENative
 * Method:    changeEncryptionProduct
 * Signature: ([B[II[II)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_changeEncryptionProduct
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jintArray, jint);

/*
 * Class:     bce_jni_natives_BCENative
 * Method:    changeDecryptionProduct
 * Signature: ([BII[II[II[B[B)I
 */
JNIEXPORT jint JNICALL Java_bce_jni_natives_BCENative_changeDecryptionProduct
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jint, jintArray, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
